module Paramorph

import TransformVariables
using LinearAlgebra

export @paramorph,
    constraint,
    constraint_with_logjac,
    unconstrain,
    intrinsic_dimension,
    parameter_fields,
    auxiliary_fields,
    nested,
    recursive,
    closed_lower,
    nonnegative,
    bounded_interval,
    correlation_matrix,
    positive_definite_matrix,
    variogram_matrix,
    positive_vector_with_sum_below,
    asymmetric_mixed,
    repeat_transform,
    joint_transform,
    polytope

include("transforms.jl")

# -----------------------------------------------------------------------------
# Geometry descriptors used by the @paramorph DSL
# -----------------------------------------------------------------------------

"""
    nested(; context...)

Use the parameter geometry declared by a nested `@paramorph` field. Keyword
arguments become the child's `context` named tuple.
"""
struct NestedSpec{C}
    context::C
end
nested(; kwargs...) = NestedSpec((; kwargs...))

"""
    recursive([count]; context...)

Use the parameter geometry of `@paramorph` objects stored recursively in a
container. A vector needs either an explicit `count` or a prototype value.
"""
struct RecursiveSpec{C}
    count::Union{Nothing,Int}
    context::C
end
recursive(; kwargs...) = RecursiveSpec(nothing, (; kwargs...))
function recursive(count::Integer; kwargs...)
    count >= 0 || throw(ArgumentError("recursive count must be nonnegative"))
    return RecursiveSpec(Int(count), (; kwargs...))
end

# -----------------------------------------------------------------------------
# Internal protocol generated by @paramorph
# -----------------------------------------------------------------------------

struct _TrustedConstruction end
const _trusted_construction = _TrustedConstruction()

is_paramorph_type(::Type) = false
parameter_fields(::Type) = ()
auxiliary_fields(::Type) = ()
auxiliary_defaults(::Type) = NamedTuple()
numeric_type(::Type) = nothing
rebind_numeric_type(T::Type, ::Type) = T
supports_type_geometry(::Type) = false

function transformation_schema(T::Type, context::NamedTuple=NamedTuple())
    throw(ArgumentError("$T does not declare a Paramorph geometry"))
end
transformation_schema(object, context::NamedTuple=NamedTuple()) =
    transformation_schema(typeof(object), context)

function _schema_from_values(T::Type, values::NamedTuple, context::NamedTuple)
    throw(ArgumentError("$T does not declare a Paramorph geometry"))
end

function _parameter_values_from_values(T::Type, values::NamedTuple, context::NamedTuple)
    throw(ArgumentError("$T does not declare Paramorph parameters"))
end

# Turn a DSL right-hand side into the TransformVariables transformation used by
# the enclosing product schema. Ordinary transforms pass through untouched.
_materialize_geometry(t, ::Type, value, ::Bool) = t

function _materialize_geometry(spec::NestedSpec, ::Type{F}, value, has_value::Bool) where {F}
    return has_value ? transformation_schema(value, spec.context) :
        transformation_schema(F, spec.context)
end

function _materialize_geometry(spec::RecursiveSpec, ::Type{F}, value, has_value::Bool) where {F}
    return has_value ? _recursive_schema(value, spec.count, spec.context) :
        _recursive_schema(F, spec.count, spec.context)
end

_geometry_value(::Any, value) = value
_geometry_value(::NestedSpec, value) = parameter_values(value)
_geometry_value(spec::RecursiveSpec, value) = _recursive_parameter_values(value)

function _recursive_schema(::Type{V}, count, context) where {E,V<:AbstractVector{E}}
    isnothing(count) && throw(ArgumentError(
        "$V needs a recursive count when its geometry is built from the type alone",
    ))
    return repeat_transform(transformation_schema(E, context), count)
end
function _recursive_schema(values::AbstractVector, count, context)
    n = isnothing(count) ? length(values) : count
    n == length(values) || throw(DimensionMismatch(
        "recursive count $n does not match vector length $(length(values))",
    ))
    if isempty(values)
        E = eltype(values)
        return repeat_transform(transformation_schema(E, context), 0)
    end
    schemas = map(value -> transformation_schema(value, context), values)
    first_schema = first(schemas)
    all(schema -> isequal(schema, first_schema), schemas) || throw(ArgumentError(
        "recursive vectors currently require elements with homogeneous parameter geometries",
    ))
    return repeat_transform(first_schema, n)
end
function _recursive_schema(::Type{T}, count, context) where {T<:Tuple}
    isnothing(count) || count == length(T.parameters) || throw(DimensionMismatch(
        "recursive count $count does not match tuple length $(length(T.parameters))",
    ))
    return TransformVariables.as(Tuple(map(type -> transformation_schema(type, context), T.parameters)))
end
function _recursive_schema(values::Tuple, count, context)
    isnothing(count) || count == length(values) || throw(DimensionMismatch(
        "recursive count $count does not match tuple length $(length(values))",
    ))
    return TransformVariables.as(map(value -> transformation_schema(value, context), values))
end
function _recursive_schema(::Type{N}, count, context) where {Names,Types,N<:NamedTuple{Names,Types}}
    isnothing(count) || count == length(Types.parameters) || throw(DimensionMismatch(
        "recursive count $count does not match named tuple length $(length(Types.parameters))",
    ))
    schemas = Tuple(map(type -> transformation_schema(type, context), Types.parameters))
    return TransformVariables.as(NamedTuple{Names}(schemas))
end
function _recursive_schema(values::NamedTuple, count, context)
    isnothing(count) || count == length(values) || throw(DimensionMismatch(
        "recursive count $count does not match named tuple length $(length(values))",
    ))
    return TransformVariables.as(map(value -> transformation_schema(value, context), values))
end

_recursive_parameter_values(values::AbstractVector) = map(parameter_values, values)
_recursive_parameter_values(values::Tuple) = map(parameter_values, values)
_recursive_parameter_values(values::NamedTuple) = map(parameter_values, values)

# -----------------------------------------------------------------------------
# Reconstruction
# -----------------------------------------------------------------------------

function _reconstruct_nested(::Type{F}, constrained::NamedTuple, context::NamedTuple) where {F}
    return _reconstruct_declared_from_type(F, constrained, context)
end
function _reconstruct_nested(prototype, ::Type{F}, constrained::NamedTuple, context::NamedTuple) where {F}
    return _reconstruct_declared_from_prototype(prototype, F, constrained, context)
end

_reconstruct_geometry(::Any, ::Type{F}, constrained) where {F} = constrained
_reconstruct_geometry(::Any, prototype, ::Type{F}, constrained) where {F} = constrained

_reconstruct_geometry(spec::NestedSpec, ::Type{F}, constrained) where {F} =
    _reconstruct_nested(F, constrained, spec.context)
_reconstruct_geometry(spec::NestedSpec, prototype, ::Type{F}, constrained) where {F} =
    _reconstruct_nested(prototype, F, constrained, spec.context)

function _reconstruct_geometry(spec::RecursiveSpec, ::Type{V}, constrained) where {E,V<:AbstractVector{E}}
    return E[_reconstruct_nested(E, value, spec.context) for value in constrained]
end
function _reconstruct_geometry(spec::RecursiveSpec, prototype::AbstractVector, ::Type{V}, constrained) where {E,V<:AbstractVector{E}}
    length(prototype) == length(constrained) || throw(DimensionMismatch("recursive vector shape changed"))
    return E[_reconstruct_nested(old, E, value, spec.context) for (old, value) in zip(prototype, constrained)]
end
function _reconstruct_geometry(spec::RecursiveSpec, ::Type{T}, constrained::Tuple) where {T<:Tuple}
    return map((type, value) -> _reconstruct_nested(type, value, spec.context), T.parameters, constrained)
end
function _reconstruct_geometry(spec::RecursiveSpec, prototype::Tuple, ::Type{T}, constrained::Tuple) where {T<:Tuple}
    return map((old, type, value) -> _reconstruct_nested(old, type, value, spec.context), prototype, T.parameters, constrained)
end
function _reconstruct_geometry(spec::RecursiveSpec, ::Type{N}, constrained::NamedTuple) where {Names,Types,N<:NamedTuple{Names,Types}}
    vals = map((type, value) -> _reconstruct_nested(type, value, spec.context), Types.parameters, Tuple(constrained))
    return NamedTuple{Names}(vals)
end
function _reconstruct_geometry(spec::RecursiveSpec, prototype::NamedTuple, ::Type{N}, constrained::NamedTuple) where {Names,Types,N<:NamedTuple{Names,Types}}
    vals = map(
        (old, type, value) -> _reconstruct_nested(old, type, value, spec.context),
        Tuple(prototype), Types.parameters, Tuple(constrained),
    )
    return NamedTuple{Names}(vals)
end

function _reconstruct_from_type(T::Type, constrained::NamedTuple)
    defaults = auxiliary_defaults(T)
    fields = map(fieldnames(T)) do field
        if hasproperty(constrained, field)
            return getproperty(constrained, field)
        elseif hasproperty(defaults, field)
            return getproperty(defaults, field)
        end
        throw(ArgumentError(
            "$T has no default for auxiliary field $field; use a prototype object",
        ))
    end
    return T(_trusted_construction, fields...)
end

function _reconstruct_from_prototype(prototype, T::Type, constrained::NamedTuple)
    fields = map(fieldnames(T)) do field
        hasproperty(constrained, field) ? getproperty(constrained, field) : getproperty(prototype, field)
    end
    return T(_trusted_construction, fields...)
end

# Macro-generated methods specialize these two hooks so that nested/recursive
# fields are reconstructed according to their declared geometry descriptor.
_reconstruct_declared_from_type(T::Type, constrained::NamedTuple, context::NamedTuple) =
    _reconstruct_from_type(T, constrained)
_reconstruct_declared_from_prototype(prototype, T::Type, constrained::NamedTuple, context::NamedTuple) =
    _reconstruct_from_prototype(prototype, T, constrained)

# -----------------------------------------------------------------------------
# Public coordinate operations
# -----------------------------------------------------------------------------

intrinsic_dimension(T::Type; context=NamedTuple()) =
    TransformVariables.dimension(transformation_schema(T, context))
intrinsic_dimension(object; context=NamedTuple()) =
    TransformVariables.dimension(transformation_schema(object, context))

parameter_values(object; context=NamedTuple()) = begin
    values = NamedTuple{fieldnames(typeof(object))}(Tuple(getfield(object, field) for field in fieldnames(typeof(object))))
    _parameter_values_from_values(typeof(object), values, context)
end

function constraint(T::Type, coordinates::AbstractVector{<:Real}; context=NamedTuple())
    supports_type_geometry(T) || throw(ArgumentError(
        "$T has value-dependent parameter geometry; use a prototype object",
    ))
    target = rebind_numeric_type(T, eltype(coordinates))
    schema = transformation_schema(target, context)
    length(coordinates) == TransformVariables.dimension(schema) || throw(DimensionMismatch(
        "expected $(TransformVariables.dimension(schema)) coordinates, got $(length(coordinates))",
    ))
    constrained = TransformVariables.transform(schema, coordinates)
    return _reconstruct_declared_from_type(target, constrained, context)
end

function constraint(prototype, coordinates::AbstractVector{<:Real}; context=NamedTuple())
    schema = transformation_schema(prototype, context)
    length(coordinates) == TransformVariables.dimension(schema) || throw(DimensionMismatch(
        "expected $(TransformVariables.dimension(schema)) coordinates, got $(length(coordinates))",
    ))
    target = rebind_numeric_type(typeof(prototype), eltype(coordinates))
    constrained = TransformVariables.transform(schema, coordinates)
    return _reconstruct_declared_from_prototype(prototype, target, constrained, context)
end

function constraint_with_logjac(T::Type, coordinates::AbstractVector{<:Real}; context=NamedTuple())
    supports_type_geometry(T) || throw(ArgumentError(
        "$T has value-dependent parameter geometry; use a prototype object",
    ))
    target = rebind_numeric_type(T, eltype(coordinates))
    schema = transformation_schema(target, context)
    length(coordinates) == TransformVariables.dimension(schema) || throw(DimensionMismatch(
        "expected $(TransformVariables.dimension(schema)) coordinates, got $(length(coordinates))",
    ))
    constrained, logjac = TransformVariables.transform_and_logjac(schema, coordinates)
    return _reconstruct_declared_from_type(target, constrained, context), logjac
end

function constraint_with_logjac(prototype, coordinates::AbstractVector{<:Real}; context=NamedTuple())
    schema = transformation_schema(prototype, context)
    length(coordinates) == TransformVariables.dimension(schema) || throw(DimensionMismatch(
        "expected $(TransformVariables.dimension(schema)) coordinates, got $(length(coordinates))",
    ))
    constrained, logjac = TransformVariables.transform_and_logjac(schema, coordinates)
    target = rebind_numeric_type(typeof(prototype), eltype(coordinates))
    return _reconstruct_declared_from_prototype(prototype, target, constrained, context), logjac
end

function unconstrain(object; context=NamedTuple())
    schema = transformation_schema(object, context)
    return TransformVariables.inverse(schema, parameter_values(object; context))
end

# -----------------------------------------------------------------------------
# Validation
# -----------------------------------------------------------------------------

function _same_constrained(a::NamedTuple, b::NamedTuple)
    keys(a) == keys(b) || return false
    return all(_same_constrained(a[name], b[name]) for name in keys(a))
end
function _same_constrained(a::AbstractArray, b::AbstractArray)
    axes(a) == axes(b) || return false
    return all(_same_constrained(x, y) for (x, y) in zip(a, b))
end
_same_constrained(a::Number, b::Number) = isapprox(a, b; nans=true)
_same_constrained(a, b) = isequal(a, b)

function validate_constrained(T::Type, values::NamedTuple)
    schema = _schema_from_values(T, values, NamedTuple())
    constrained = _parameter_values_from_values(T, values, NamedTuple())
    coordinates = try
        TransformVariables.inverse(schema, constrained)
    catch error
        error isa Union{DomainError, ArgumentError, DimensionMismatch} || rethrow()
        throw(DomainError(values, "the parameter fields of $T do not satisfy their declared geometry"))
    end
    roundtrip = TransformVariables.transform(schema, coordinates)
    _same_constrained(constrained, roundtrip) || throw(DomainError(
        values,
        "the parameter fields of $T are not in the image of their declared geometry",
    ))
    return nothing
end

# -----------------------------------------------------------------------------
# @paramorph parser and code generation
# -----------------------------------------------------------------------------

_field_name_from_decl(expr) = expr isa Expr && expr.head == :(::) && expr.args[1] isa Symbol ? expr.args[1] : nothing

function _split_parameter_line(line)
    # Julia parses `field::Type ~ geometry` as the infix call `~(field::Type, geometry)`.
    line isa Expr && line.head == :call && line.args[1] == :~ || return nothing
    length(line.args) == 3 || error("parameter declarations must use `field::Type ~ geometry`")
    declaration, geometry = line.args[2], line.args[3]
    declaration isa Expr && declaration.head == :(::) ||
        error("the left side of `~` must be a typed field declaration")
    name = declaration.args[1]
    name isa Symbol || error("parameter field names must be symbols")
    return name, declaration.args[2], geometry
end

function _split_geometry_macro(line)
    line isa Expr && line.head == :macrocall || return nothing
    macro_name = line.args[1]
    macro_name == Symbol("@geometry") || return nothing
    payload = line.args[end]
    payload isa Expr && payload.head == :call && payload.args[1] == :~ ||
        error("use `@geometry (a, b, ...) ~ transformation`")
    lhs, geometry = payload.args[2], payload.args[3]
    names = if lhs isa Symbol
        (lhs,)
    elseif lhs isa Expr && lhs.head == :tuple && all(x -> x isa Symbol, lhs.args)
        Tuple(lhs.args)
    else
        error("@geometry must name one or more fields")
    end
    return names, geometry
end

function _contains_field_reference(expr, fields::Set{Symbol})
    expr isa QuoteNode && return false
    expr isa Symbol && return expr in fields
    expr isa Expr || return false
    return any(arg -> _contains_field_reference(arg, fields), expr.args)
end

function _type_parameter_parts(parameters)
    names = Symbol[]
    for parameter in parameters
        if parameter isa Symbol
            push!(names, parameter)
        elseif parameter isa Expr && parameter.head in (:<:, :>:)
            push!(names, parameter.args[1])
        else
            error("unsupported type parameter `$parameter`")
        end
    end
    return names
end

"""
    @paramorph T struct Model{...,T<:Real}
        auxiliary::A
        parameter::T ~ transform
        child::Child{T} ~ nested(key=value)
    end

Declare parameter geometry next to ordinary Julia storage types. `::` describes
storage; `~` describes geometry. Fields without `~` are auxiliary.

A struct may alternatively declare one coupled geometry:

    @paramorph T struct Interval{T<:Real}
        lower::T
        upper::T
        @geometry (lower, upper) ~ ordered_interval_transform()
    end
"""
macro paramorph(numeric_parameter, expr)
    numeric_parameter isa Symbol || error("the numeric parameter passed to @paramorph must be a symbol")
    expr isa Expr && expr.head == :struct || error("@paramorph must wrap a struct definition")
    expr.args[1] && error("@paramorph does not support mutable structs")

    struct_sig = expr.args[2]
    declaration, supertype = if struct_sig isa Expr && struct_sig.head == :(<:)
        struct_sig.args[1], struct_sig.args[2]
    else
        struct_sig, nothing
    end

    if declaration isa Expr && declaration.head == :curly
        struct_name = declaration.args[1]
        type_params = collect(declaration.args[2:end])
    elseif declaration isa Symbol
        struct_name = declaration
        type_params = Any[]
    else
        error("unsupported struct declaration")
    end
    struct_name isa Symbol || error("unsupported struct name")

    type_args = _type_parameter_parts(type_params)
    numeric_index = findfirst(==(numeric_parameter), type_args)
    numeric_index === nothing && error(
        "numeric parameter $numeric_parameter must be explicitly declared by the struct",
    )
    numeric_parameter_decl = type_params[numeric_index]

    raw_lines = [line for line in expr.args[3].args if !(line isa LineNumberNode)]
    field_records = NamedTuple[]
    geometry_macro = nothing

    for line in raw_lines
        global_geometry = _split_geometry_macro(line)
        if global_geometry !== nothing
            geometry_macro === nothing || error("only one @geometry declaration is allowed")
            geometry_macro = global_geometry
            continue
        end

        parameter = _split_parameter_line(line)
        if parameter !== nothing
            name, storage, geometry = parameter
            push!(field_records, (; name, storage, geometry, is_parameter=true, default=nothing))
            continue
        end

        has_default = line isa Expr && line.head == :(=)
        declaration_line = has_default ? line.args[1] : line
        default = has_default ? line.args[2] : nothing
        name = _field_name_from_decl(declaration_line)
        name === nothing && error(
            "@paramorph struct bodies may contain only typed fields, `field::Type ~ geometry`, and @geometry",
        )
        push!(field_records, (;
            name,
            storage=declaration_line.args[2],
            geometry=nothing,
            is_parameter=false,
            default,
        ))
    end

    field_names = [r.name for r in field_records]
    length(unique(field_names)) == length(field_names) || error("duplicate field declaration")

    if geometry_macro !== nothing
        any(r -> r.is_parameter, field_records) && error(
            "do not mix field-level `~` declarations with a global @geometry declaration",
        )
        geometry_names, global_geometry = geometry_macro
        all(name -> name in field_names, geometry_names) || error("@geometry names an unknown field")
        field_records = [merge(r, (; is_parameter=r.name in geometry_names)) for r in field_records]
    else
        global_geometry = nothing
    end

    parameter_names = Tuple(r.name for r in field_records if r.is_parameter)
    auxiliary_names = Tuple(r.name for r in field_records if !r.is_parameter)
    isempty(parameter_names) && error("@paramorph requires at least one parameter field")

    clean_fields = [:( $(r.name)::$(r.storage) ) for r in field_records]
    all_values = Expr(:tuple, [:( $(r.name) = $(r.name) ) for r in field_records]...)
    defaults = Expr(:tuple, [:( $(r.name) = $(r.default) ) for r in field_records if !r.is_parameter && r.default !== nothing]...)

    field_set = Set(field_names)
    runtime_dependent = if global_geometry === nothing
        any(r -> r.is_parameter && _contains_field_reference(r.geometry, field_set), field_records)
    else
        _contains_field_reference(global_geometry, field_set)
    end

    # Bind every field name while evaluating runtime geometry expressions.
    bind_from_values = [:( $(r.name) = getproperty(values, $(QuoteNode(r.name))) ) for r in field_records]

    if global_geometry === nothing
        value_schema_pairs = Any[]
        type_schema_pairs = Any[]
        parameter_value_pairs = Any[]
        type_reconstruct_pairs = Any[]
        prototype_reconstruct_pairs = Any[]

        for r in field_records
            r.is_parameter || continue
            name, geometry = r.name, r.geometry
            push!(value_schema_pairs, :(
                $name = Paramorph._materialize_geometry(
                    $geometry,
                    fieldtype(S, $(QuoteNode(name))),
                    getproperty(values, $(QuoteNode(name))),
                    true,
                )
            ))
            push!(type_schema_pairs, :(
                $name = Paramorph._materialize_geometry(
                    $geometry,
                    fieldtype(S, $(QuoteNode(name))),
                    nothing,
                    false,
                )
            ))
            push!(parameter_value_pairs, :(
                $name = Paramorph._geometry_value(
                    $geometry,
                    getproperty(values, $(QuoteNode(name))),
                )
            ))
            push!(type_reconstruct_pairs, :(
                $name = Paramorph._reconstruct_geometry(
                    $geometry,
                    fieldtype(S, $(QuoteNode(name))),
                    getproperty(constrained, $(QuoteNode(name))),
                )
            ))
            push!(prototype_reconstruct_pairs, :(
                $name = Paramorph._reconstruct_geometry(
                    $geometry,
                    getfield(prototype, $(QuoteNode(name))),
                    fieldtype(S, $(QuoteNode(name))),
                    getproperty(constrained, $(QuoteNode(name))),
                )
            ))
        end
        value_schema_expr = :(Paramorph.TransformVariables.as($(Expr(:tuple, value_schema_pairs...))))
        type_schema_expr = :(Paramorph.TransformVariables.as($(Expr(:tuple, type_schema_pairs...))))
        parameter_values_expr = Expr(:tuple, parameter_value_pairs...)
        type_reconstructed_parameters = Dict(r.name => pair.args[2] for (r, pair) in zip(
            [r for r in field_records if r.is_parameter], type_reconstruct_pairs,
        ))
        prototype_reconstructed_parameters = Dict(r.name => pair.args[2] for (r, pair) in zip(
            [r for r in field_records if r.is_parameter], prototype_reconstruct_pairs,
        ))
    else
        value_schema_expr = global_geometry
        type_schema_expr = global_geometry
        parameter_values_expr = Expr(:tuple, [:( $name = getproperty(values, $(QuoteNode(name))) ) for name in parameter_names]...)
        type_reconstructed_parameters = Dict(name => :(getproperty(constrained, $(QuoteNode(name)))) for name in parameter_names)
        prototype_reconstructed_parameters = copy(type_reconstructed_parameters)
    end

    # Reconstruction expressions preserve prototype auxiliary values or use declared defaults.
    type_field_values = Any[]
    prototype_field_values = Any[]
    for r in field_records
        if r.is_parameter
            push!(type_field_values, get(type_reconstructed_parameters, r.name, :(getproperty(constrained, $(QuoteNode(r.name))))))
            push!(prototype_field_values, get(prototype_reconstructed_parameters, r.name, :(getproperty(constrained, $(QuoteNode(r.name))))))
        else
            if r.default === nothing
                push!(type_field_values, :(throw(ArgumentError(string(
                    S, " has no default for auxiliary field ", $(string(r.name)), "; use a prototype object",
                )))))
            else
                push!(type_field_values, r.default)
            end
            push!(prototype_field_values, :(getfield(prototype, $(QuoteNode(r.name)))))
        end
    end

    generated_declaration = Expr(:curly, struct_name, type_params...)
    generated_struct_sig = isnothing(supertype) ? generated_declaration : Expr(:(<:), generated_declaration, supertype)

    # Validating and trusted constructors.
    constructor = quote
        function $struct_name{$(type_args...)}(
            ::Paramorph._TrustedConstruction,
            $(clean_fields...),
        ) where {$(type_params...)}
            return new{$(type_args...)}($(field_names...))
        end
        function $struct_name{$(type_args...)}($(clean_fields...)) where {$(type_params...)}
            values = $all_values
            Paramorph.validate_constrained($struct_name{$(type_args...)}, values)
            return new{$(type_args...)}($(field_names...))
        end
    end

    inferred_params = [p for (p, name) in zip(type_params, type_args) if name != numeric_parameter]
    inferred_args = [name for name in type_args if name != numeric_parameter]
    inferred_constructor = if isempty(inferred_args)
        quote
            function $struct_name($(clean_fields...)) where {$numeric_parameter_decl}
                return $struct_name{$(type_args...)}($(field_names...))
            end
        end
    else
        quote
            function $struct_name{$(inferred_args...)}($(clean_fields...)) where {$(inferred_params...), $numeric_parameter_decl}
                return $struct_name{$(type_args...)}($(field_names...))
            end
        end
    end

    generated_body = Expr(:block, clean_fields..., constructor.args...)
    struct_definition = Expr(:struct, false, generated_struct_sig, generated_body)

    rebound_args = [name == numeric_parameter ? :ParamorphNumeric : name for name in type_args]

    type_schema_body = runtime_dependent ? :(throw(ArgumentError(string(
        S, " has parameter geometry depending on runtime field values; use a prototype object",
    )))) : type_schema_expr

    return esc(quote
        $struct_definition
        $inferred_constructor

        Paramorph.is_paramorph_type(::Type{<:$struct_name}) = true
        Paramorph.parameter_fields(::Type{<:$struct_name}) = $parameter_names
        Paramorph.auxiliary_fields(::Type{<:$struct_name}) = $auxiliary_names
        function Paramorph.auxiliary_defaults(
            ::Type{<:$struct_name{$(type_args...)}}
        ) where {$(type_params...)}
            return $defaults
        end
        Paramorph.numeric_type(::Type{<:$struct_name{$(type_args...)}}) where {$(type_params...)} = $numeric_parameter
        Paramorph.supports_type_geometry(::Type{<:$struct_name}) = $(!runtime_dependent)

        function Paramorph.rebind_numeric_type(
            ::Type{<:$struct_name{$(type_args...)}},
            ::Type{ParamorphNumeric},
        ) where {$(type_params...), ParamorphNumeric<:Real}
            return $struct_name{$(rebound_args...)}
        end

        function Paramorph._schema_from_values(
            ::Type{S}, values::NamedTuple, context::NamedTuple,
        ) where {$(type_params...), S<:$struct_name{$(type_args...)}}
            $(bind_from_values...)
            return $value_schema_expr
        end

        function Paramorph.transformation_schema(
            object::S, context::NamedTuple=NamedTuple(),
        ) where {$(type_params...), S<:$struct_name{$(type_args...)}}
            values = NamedTuple{fieldnames(S)}(Tuple(getfield(object, f) for f in fieldnames(S)))
            return Paramorph._schema_from_values(S, values, context)
        end

        function Paramorph.transformation_schema(
            ::Type{S}, context::NamedTuple=NamedTuple(),
        ) where {$(type_params...), S<:$struct_name{$(type_args...)}}
            return $type_schema_body
        end

        function Paramorph._parameter_values_from_values(
            ::Type{S}, values::NamedTuple, context::NamedTuple,
        ) where {$(type_params...), S<:$struct_name{$(type_args...)}}
            $(bind_from_values...)
            return $parameter_values_expr
        end

        function Paramorph._reconstruct_declared_from_type(
            ::Type{S}, constrained::NamedTuple, context::NamedTuple,
        ) where {$(type_params...), S<:$struct_name{$(type_args...)}}
            $(runtime_dependent ? :(throw(ArgumentError(string(
                S, " has value-dependent parameter geometry; use a prototype object",
            )))) : nothing)
            return S(Paramorph._trusted_construction, $(type_field_values...))
        end

        function Paramorph._reconstruct_declared_from_prototype(
            prototype::$struct_name,
            ::Type{S},
            constrained::NamedTuple,
            context::NamedTuple,
        ) where {$(type_params...), S<:$struct_name{$(type_args...)}}
            values = NamedTuple{fieldnames(typeof(prototype))}(
                Tuple(getfield(prototype, f) for f in fieldnames(typeof(prototype)))
            )
            $(bind_from_values...)
            return S(Paramorph._trusted_construction, $(prototype_field_values...))
        end
    end)
end

macro paramorph(expr)
    error("Paramorph 0.0.3 requires an explicit numeric type parameter, e.g. `@paramorph T struct Foo{T<:Real} ... end`")
end

end # module
